# Generated by Django 2.2.14 on 2021-07-06 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=300, null=True)),
                ('resources', models.TextField(blank=True, default='--', null=True)),
                ('level', models.IntegerField(blank=True, default=0, null=True)),
                ('hints', models.TextField(blank=True, default='--', null=True)),
                ('hintNumber', models.IntegerField(blank=True, default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('level', models.IntegerField(blank=True, default=0, null=True)),
                ('submission_time', models.DateTimeField(blank=True, null=True)),
                ('skipsLeft', models.IntegerField(blank=True, default=1, null=True)),
                ('hintsLeft', models.IntegerField(blank=True, default=3, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
